skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
oracle_demo = "4k8Nacw6CNRhzGdKYDvc8hMhArZ82njgWAia41dRDRbi"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
